#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Integration tests for pull request review comment REST APIs.
"""

from __future__ import annotations

from pathlib import Path
from uuid import uuid4
from typing import Any
import pytest

from core.api import GitHubRESTCrawler
from core.config import OUTPUT_DIR_TEST, get_github_token_test

TEST_REPO_OWNER = "edwardzcn-decade"
TEST_REPO_NAME = "gh-easy-crawler"
# TEST_PULL_REQUEST_HEAD = "v0.4.1"
# TEST_PULL_REQUEST_BASE = "main"


def _cleanup_output_artifacts():
    """Remove JSON files generated by review comment tests."""
    output_path = Path(OUTPUT_DIR_TEST)
    output_path.mkdir(parents=True, exist_ok=True)
    patterns = [
        "pull_review_comments_repo_*_page_*.json",
        "pull_*_review_comments_*_page_*.json",
        "pull_*_review_comment_*_created.json",
        "pull_review_comment_*_updated.json",
        "pull_review_comment_*_deleted.json",
        "pull_*_review_comment_*_replied_*.json",
    ]
    for pattern in patterns:
        for path in output_path.glob(pattern):
            try:
                path.unlink()
            except FileNotFoundError:
                continue


@pytest.fixture(scope="module")
def crawler() -> GitHubRESTCrawler:
    token = get_github_token_test()
    if not token:
        pytest.skip("GITHUB_TOKEN is required to run GitHub API tests.")
    return GitHubRESTCrawler(
        TEST_REPO_OWNER,
        TEST_REPO_NAME,
        token,
        OUTPUT_DIR_TEST,
    )


@pytest.fixture(scope="module", autouse=True)
def prepare_environment():
    """Ensure review comment artifacts are cleaned up before/after tests."""
    _cleanup_output_artifacts()
    yield
    _cleanup_output_artifacts()


@pytest.fixture(scope="module")
def special_pull(crawler: GitHubRESTCrawler) -> dict:
    # Fetch special pulll
    pulls = crawler.list_repo_pulls(state="all", per_page=30, page=1)
    if not pulls:
        pulls = crawler.list_repo_pulls(state="all", per_page=30, page=1)
    if not pulls:
        pytest.skip("Test repository has no pull requests to inspect.")
    return pulls[-13]


@pytest.fixture
def review_comment_context(
    crawler: GitHubRESTCrawler, special_pull: dict
) -> dict[str, str | int]:
    pull_number = special_pull["number"]
    commits = crawler.list_pull_commits(pull_number, per_page=1, page=1)
    files = crawler.list_pull_files(pull_number, per_page=1, page=1)
    if not commits or not files:
        pytest.skip("Need at least one commit and changed file to post review comments.")
    return {
        "pull_number": pull_number,
        "commit_id": commits[-1]["sha"],
        "path": files[0]["filename"],
    }


def test_list_repo_pull_review_comments_not_empty(crawler: GitHubRESTCrawler):
    comments = crawler.list_repo_pull_review_comments(per_page=5, page=1)
    assert isinstance(comments, list)
    assert len(comments) > 0


def test_list_pull_review_comments_not_empty(
    crawler: GitHubRESTCrawler, special_pull: dict
):
    pull_number = special_pull["number"]
    output_path = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_comments_None_page_1.json"
    )
    if output_path.exists():
        output_path.unlink()

    comments = crawler.list_pull_review_comments(pull_number, per_page=5, page=1)
    print(output_path)
    assert output_path.exists()
    assert isinstance(comments, list)
    assert len(comments) > 0


def test_review_comment_lifecycle_left_one(
    crawler: GitHubRESTCrawler, review_comment_context: dict[str, Any]
):
    pull_number = review_comment_context["pull_number"]
    commit_id = review_comment_context["commit_id"]
    path = review_comment_context["path"]
    base_body = f"[UT][REST] Review comment {uuid4()}"

    # Will receive error message for a resolved pr.
    # status code 422 and the errors[0].message == "could not be resolved"
    try:
        created = crawler.create_pull_review_comment(
            pull_number=pull_number,
            body=base_body,
            commit_id=commit_id,
            path=path,
            line=1,
            side="RIGHT",
        )
    except Exception as e:
        assert 
    comment_id = created["id"]
    created_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_comment_{comment_id}_created.json"
    )
    assert created["body"] == base_body
    assert created_output.exists()

    created_second = crawler.create_pull_review_comment(
        pull_number=pull_number,
        body=base_body,
        commit_id=commit_id,
        path=path,
        line=2,
        side="RIGHT",
    )
    created_second_id = created_second["id"]
    second_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_comment_{created_second_id}_created.json"
    )
    assert created_second["body"] == base_body
    assert second_output.exists()

    fetched = crawler.get_pull_review_comment(comment_id)
    assert fetched["id"] == comment_id

    updated_body = f"{base_body} :: updated"
    updated = crawler.update_pull_review_comment(comment_id, updated_body)
    updated_output = (
        Path(OUTPUT_DIR_TEST) / f"pull_review_comment_{comment_id}_updated.json"
    )
    assert updated["body"] == updated_body
    assert updated_output.exists()

    reply_body = f"{base_body} :: reply"
    reply = crawler.create_reply_pull_review_comment(
        pull_number=pull_number, comment_id=comment_id, body=reply_body
    )
    reply_id = reply["id"]
    reply_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_comment_{comment_id}_replied_{reply_id}.json"
    )
    assert reply["in_reply_to_id"] == comment_id
    assert reply_output.exists()

    second_reply = crawler.create_reply_pull_review_comment(
        pull_number=pull_number,comment_id=created_second_id, body=reply_body
    )
    second_reply_id = second_reply["id"]
    second_reply_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_comment_{created_second_id}_replied_{second_reply_id}.json"
    )
    assert second_reply["in_reply_to_id"] == created_second_id
    assert second_reply_output.exists()

    assert crawler.delete_pull_review_comment(reply_id) is True

    assert crawler.delete_pull_review_comment(comment_id) is True
