#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Integration tests for pull request review REST APIs.
"""

from __future__ import annotations

from pathlib import Path
from uuid import uuid4

import pytest

from core.api import GitHubRESTCrawler
from core.config import OUTPUT_DIR_TEST, get_github_token_test

TEST_REPO_OWNER = "edwardzcn-decade"
TEST_REPO_NAME = "gh-easy-crawler"


def _cleanup_output_artifacts():
    """Remove JSON files generated by review tests."""
    output_path = Path(OUTPUT_DIR_TEST)
    output_path.mkdir(parents=True, exist_ok=True)
    patterns = [
        "pull_*_reviews_page_*.json",
        "pull_*_review_*_created.json",
        "pull_*_review_*_updated.json",
        "pull_*_review_*_deleted.json",
        "pull_*_review_*_submitted.json",
        "pull_*_review_*_dismissed.json*",
        "pull_*_review_*_comments_page_*.json",
    ]
    for pattern in patterns:
        for path in output_path.glob(pattern):
            try:
                path.unlink()
            except FileNotFoundError:
                continue


@pytest.fixture(scope="module")
def crawler() -> GitHubRESTCrawler:
    token = get_github_token_test()
    if not token:
        pytest.skip("GITHUB_TOKEN is required to run GitHub API tests.")
    return GitHubRESTCrawler(
        TEST_REPO_OWNER,
        TEST_REPO_NAME,
        token,
        OUTPUT_DIR_TEST,
    )


@pytest.fixture(scope="module", autouse=True)
def prepare_environment():
    """Ensure review artifacts are cleaned up before/after tests."""
    _cleanup_output_artifacts()
    yield
    _cleanup_output_artifacts()


@pytest.fixture(scope="module")
def sample_pull(crawler: GitHubRESTCrawler) -> dict:
    pulls = crawler.list_repo_pulls(state="open", per_page=30, page=1)
    if not pulls:
        print("⚠️ TEST WARNING: Test repository has no open pull requests. Some tests may skip.")
        pytest.skip("Test repository has no open pull requests to inspect.")
    return pulls[0]


def test_list_pull_reviews_creates_output(
    crawler: GitHubRESTCrawler, sample_pull: dict
):
    pull_number = sample_pull["number"]
    output_path = (
        Path(OUTPUT_DIR_TEST) / f"pull_{pull_number}_reviews_page_1.json"
    )
    if output_path.exists():
        output_path.unlink()

    reviews = crawler.list_pull_reviews(pull_number, per_page=30, page=1)

    assert isinstance(reviews, list)
    assert output_path.exists()


def test_create_update_and_delete_pending_review(
    crawler: GitHubRESTCrawler, sample_pull: dict
):
    pull_number = sample_pull["number"]
    base_body = f"[UT][REST] Pending review {uuid4()}"
    created = crawler.create_pull_review(pull_number, body=base_body)
    review_id = created["id"]
    created_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_{review_id}_created.json"
    )
    assert created_output.exists()
    assert created["body"] == base_body

    fetched = crawler.get_pull_review(pull_number, review_id)
    assert fetched["id"] == review_id

    updated_body = f"{base_body} :: updated"
    updated = crawler.update_pull_review(pull_number, review_id, updated_body)
    updated_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_{review_id}_updated.json"
    )
    assert updated_output.exists()
    assert updated["body"] == updated_body

    deleted = crawler.delete_pull_pending_review(pull_number, review_id)
    deleted_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_{review_id}_deleted.json"
    )
    assert deleted_output.exists()
    assert isinstance(deleted, dict)


def test_submit_review(
    crawler: GitHubRESTCrawler, sample_pull: dict
):
    pull_number = sample_pull["number"]
    base_body = f"[UT][REST] Review {uuid4()}"
    created = crawler.create_pull_review(pull_number, body=base_body)
    review_id = created["id"]

    comments = crawler.list_pull_review_comments_for_review(
        pull_number, review_id, per_page=30, page=1
    )
    comments_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_{review_id}_comments_page_1.json"
    )
    assert isinstance(comments, list)
    assert comments_output.exists()

    submitted = crawler.submit_pull_review(
        pull_number, review_id, event="COMMENT", body=f"{base_body} :: submit"
    )
    submitted_output = (
        Path(OUTPUT_DIR_TEST)
        / f"pull_{pull_number}_review_{review_id}_submitted.json"
    )
    assert submitted_output.exists()
    assert submitted["state"] == "COMMENTED"

# TODO test_dismiss_review