#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Integration tests for pull request review request REST APIs.
"""

from __future__ import annotations

import os
from pathlib import Path
from requests import HTTPError
import pytest

from core.api import GitHubRESTCrawler
from core.config import OUTPUT_DIR_TEST, get_github_token_test

TEST_REPO_OWNER = "edwardzcn-decade"
TEST_REPO_NAME = "gh-easy-crawler"


def _cleanup_output_artifacts():
    """Remove JSON files generated by review request tests."""
    output_path = Path(OUTPUT_DIR_TEST)
    output_path.mkdir(parents=True, exist_ok=True)
    patterns = [
        "pull_*_requested_reviewers.json",
        "pull_*_requested_reviewers_added.json",
        "pull_*_requested_reviewers_removed.json",
    ]
    for pattern in patterns:
        for path in output_path.glob(pattern):
            try:
                path.unlink()
            except FileNotFoundError:
                continue


@pytest.fixture(scope="module")
def crawler() -> GitHubRESTCrawler:
    token = get_github_token_test()
    if not token:
        pytest.skip("GITHUB_TOKEN is required to run GitHub API tests.")
    return GitHubRESTCrawler(
        TEST_REPO_OWNER,
        TEST_REPO_NAME,
        token,
        OUTPUT_DIR_TEST,
    )


@pytest.fixture(scope="module", autouse=True)
def prepare_environment():
    """Ensure review request artifacts are cleaned up before/after tests."""
    _cleanup_output_artifacts()
    yield
    _cleanup_output_artifacts()


@pytest.fixture(scope="module")
def sample_pull(crawler: GitHubRESTCrawler) -> dict:
    pulls = crawler.list_repo_pulls(state="open", per_page=30, page=1)
    if not pulls:
        pytest.skip("Test repository has no open pull requests to inspect.")
    return pulls[0]


@pytest.fixture(scope="module")
def reviewer_login() -> str:
    reviewer = TEST_REPO_OWNER
    if not reviewer:
        pytest.skip("Set TEST_REPO_OWNER to run review-request tests.")
    return reviewer


def test_list_pull_requested_reviewers_creates_output(
    crawler: GitHubRESTCrawler, sample_pull: dict
):
    pull_number = sample_pull["number"]
    output_path = (
        Path(OUTPUT_DIR_TEST) / f"pull_{pull_number}_requested_reviewers.json"
    )
    if output_path.exists():
        output_path.unlink()

    payload = crawler.list_pull_requested_reviewers(pull_number)

    assert isinstance(payload, dict)
    assert output_path.exists()


def test_request_and_remove_pull_reviewers(
    crawler: GitHubRESTCrawler, sample_pull: dict, reviewer_login: str
):
    pull_number = sample_pull["number"]
    cleanup_required = False
    try:
        added = crawler.request_pull_reviewers(
            pull_number, reviewers=[reviewer_login]
        )
        cleanup_required = True
        added_output = (
            Path(OUTPUT_DIR_TEST)
            / f"pull_{pull_number}_requested_reviewers_added.json"
        )
        assert added_output.exists()
        assert "requested_reviewers" in added
    except HTTPError as e_422:
        # Response Status Code: 422
        # Response Content: {"message":"Review cannot be requested from pull request author.", ...}
        print(e_422.strerror)
    finally:
        if cleanup_required:
            removed = crawler.remove_pull_reviewers(
                pull_number, reviewers=[reviewer_login]
            )
            removed_output = (
                Path(OUTPUT_DIR_TEST)
                / f"pull_{pull_number}_requested_reviewers_removed.json"
            )
            assert removed_output.exists()
            assert isinstance(removed, dict)
